[package]
name = "apresentation"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.20"
include-wgsl-oil = { version = "0.2" }
winit = { version = "0.30" }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
palette = "0.7"

pollster = "0.3"

log = "*"
pretty_env_logger = "0.5"

anyhow = "*"
bytemuck = { version = "1.12", features = ["derive"] }
once_cell = "*"
dynstack = "0.4"
downcast-rs = "1.2"

glam = "0.27"
mlua = { version = "0.9", features = ["luajit", "vendored", "send"] }
rand = "0.8"
regex = "1"

impl-trait-for-tuples = "0.2"
xxhash-rust = { version = "0.8", features = ["xxh3", "const_xxh3"] }
try-iterator = "1"
hex = "0.4"

serde = "1"
toml = "0.8"