name: Rust Release build

on:
  public

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        rustup target add x86_64-pc-windows-gnu
        rustup target add x86_64-unknown-linux-gnu
        sudo apt update
        sudo apt install -y g++-mingw-w64-x86-64
    - name: Compile for Linux
      run: cargo build --verbose --target x86_64-unknown-linux-gnu --release
    - name: Compile for Windows
      run: cargo build --verbose --target x86_64-pc-windows-gnu --release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          target
          !target/debug
          !target/**/**/build
          !target/**/**/deps
          !target/**/**/incremental
          !target/**/**/.fingerprint